

networks:
  app-network:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_base
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 19031988
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_DEFAULT_SCHEMA: public

    depends_on:
      - db
      - migrate
    networks:
      - app-network


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: public
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19031988
    ports:
      - "5432:5432"
    volumes:
          - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - app-network

  migrate:
    image: liquibase:latest
    entrypoint: ["sh", "-c", "liquibase --changeLogFile=/db/changelog/db.changelog-master.yaml --url=jdbc:postgresql://db:5432/test_base --username=postgres --password=19031988 --defaultSchemaName=public update"]
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/changelog:/db/changelog
    networks:
      - app-network
